---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devopsmaonamassa"
  tasks:
    - name: Configurar hosts lab Ansible
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "10.10.1.2 control-node"
        - "10.10.1.3 app01"
        - "10.10.1.4 db01"
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
    