Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vbguest.iso_path = '../../VBoxGuestAdditions_7.0.14.iso'
    config.vbguest.auto_update = false
    config.vm.network "private_network", ip: "10.10.1.20" 
    config.vm.synced_folder ".", "/vagrant", type: "nfs"
    config.vm.provision "shell", path:"provision.sh"
end