Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "app01"
    config.vbguest.iso_path = '../../VBoxGuestAdditions_7.0.14.iso'
    config.vbguest.auto_update = false
    config.vm.network "private_network", ip: "10.10.1.3" 
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.provision "shell", path: "provision.sh" 
  
  end
  