Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "db01"
    config.vbguest.iso_path = '../../VBoxGuestAdditions_7.0.14.iso'
    config.vbguest.auto_update = false
    config.vm.network "private_network", ip: "10.10.1.4" 
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.vm.provision "shell", path: "provision.sh" 
  end